### ISSUE TITLE
zss

### ISSUE THREAD

**Issue by KOLANICH** [kaitaiStructCompile/issue_templates_testing#1]
### Format stub

```yaml
meta:
  id: # MANDATORY.
  title: # MANDATORY.
  application: 
  file-extension: # todo: https://extension.nirsoft.net/
  xref:
    ansi: 
    din: 
    forensicswiki: # https://forensicswiki.xyz/
    fileformat: # https://www.fileformat.info
    incits: 
    iso: 
    justsolve: # http://fileformats.archiveteam.org/wiki/
    loc: # https://www.loc.gov/preservation/digital/formats/
    mime: 
    pronom: # https://www.nationalarchives.gov.uk/pronom/fmt/
      - x-fmt/
    rfc: 
    uti: 
    ffdg: # https://docs.fileformat.com
    wikidata: Q

doc: | # MANDATORY


doc-ref: # MANDATORY.
  - aaa
  - 
  -
```
